[WIP]Box Service の Push 実装変更
intelligent-retail/smart-store pull request #63
Opened 2020-06-08 12:34 UTC by masatoru

2020-09-21 04:49 UTC, dzeyelid commented
@masatoru `src/test/SendPush.Sample` もこちらのプルリクエストに含めるのであれば、 SendPush.Sample の使い方を README に記載いただけますか～？

2020-09-21 05:11 UTC, dzeyelid requested changes
少なくとも `local.settings.json` に書いたコメント内容は対応いただきたいです。御確認をお願い足します 🙏

2020-09-21 05:11 UTC, dzeyelid commented on src/box-service/BoxManagementService/Utilities/NotificationUtility.cs
> +                Console.WriteLine($"Android device token={deviceId}");
実際に Azure Functions にアップロードして動かすときは Console への出力はない方がいいと思うので、特に不要であれば削除いただくか、ローカル起動時のみ出力するなど調整されるとよいかと思いました 🙏 

逆にログに出すべきなら、Application Insights に出すとよさそうです。
https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-monitoring?tabs=cmd#log-custom-telemetry-in-c-functions

他にもいくつかあるのでご確認をお願いします。

2020-09-21 05:11 UTC, dzeyelid commented on src/box-service/BoxManagementService/Utilities/NotificationUtility.cs
> +        /// <param name="token">8888AAAABBBBCCCC99998888DDDDEEEE4444333300001111FFFF555566667777</param>
このトークンのような文字列は、記載されてても問題ないですか？

2020-09-21 05:11 UTC, dzeyelid commented on src/test/SendPush.Sample/local.settings.json
> +{
将来的に、誰かの設定が誤ってコミットしないように、 `local.settings.json` は `.gitignore` に含めてコミットできないようにして、 `local.settings.example.json` というファイル名でこちらのサンプルファイルをコミットしてもらいたいです。

2020-09-26 23:16 UTC, masatoru commented on src/box-service/BoxManagementService/Utilities/NotificationUtility.cs
> +        /// <param name="token">8888AAAABBBBCCCC99998888DDDDEEEE4444333300001111FFFF555566667777</param>
これはiOSの形式としての例なのでこのままでOKです。

2020-09-26 23:20 UTC, masatoru commented on src/box-service/BoxManagementService/Utilities/NotificationUtility.cs
> +                Console.WriteLine($"Android device token={deviceId}");
これはConsoleで動かすだけのサンプルなのでFunctionsで動作させることはそもそも想定してないです。この後の改善案としてFunctions対応にするのもよいかもぐらいで良いかなと。

2020-09-26 23:30 UTC, masatoru commented on src/box-service/BoxManagementService/Utilities/NotificationUtility.cs
> +                Console.WriteLine($"Android device token={deviceId}");
すいません、勘違いです。当初はテスト目的でConsoleアプリで動作する作ったのですが、それをライブラリで共有するようにしたので、そのまま Console.WriteLine が残ってしまってるということですね。これは削除します。

2020-09-26 23:41 UTC, masatoru commented on src/box-service/BoxManagementService/Utilities/NotificationUtility.cs
> +                Console.WriteLine($"Android device token={deviceId}");
というより、ConsoleプログラムにもILoggerが組み込まれているのでそちらに切り替えました。

2020-09-26 23:41 UTC, masatoru commented on src/test/SendPush.Sample/local.settings.json
> +{
修正しました。

2020-09-26 23:49 UTC, masatoru commented
> @masatoru `src/test/SendPush.Sample` もこちらのプルリクエストに含めるのであれば、 SendPush.Sample の使い方を README に記載いただけますか～？

#64 こっちで書きますね。

2020-09-30 16:41 UTC, dzeyelid approved these changes
ご対応ありがとうございました！デプロイしての確認でもOKでした！

2020-09-30 16:41 UTC, merged