[WIP]Xamarin 側の Push 実装変更
intelligent-retail/smart-store pull request #64
Opened 2020-06-08 12:55 UTC by masatoru

2020-09-30 17:47 UTC, dzeyelid requested changes
とっても細かいところで恐縮ですが、いくつかコメントをしました。

少なくとも、Mock で参照している画像は変更いただきたいです。

ご確認をお願いいたします。 🙏

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Utilities/Mock.cs
> +                            ImageUrls=new []{ "https://www.morinaga.co.jp/dars/images/item_01_01.png" }
この画像、こちらに差し替えられませんか？
https://github.com/intelligent-retail/smart-store/raw/master/src/arm-template/sample-data/public/item-service/images/testimage.png

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Views/LoginPage.xaml.cs
> +            // btnStartShopping.IsVisible = false;
このコメントアウトの行、不要でしたら削除をお願いします。

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Views/LoginPage.xaml.cs
> +                        // btnStartShopping.IsVisible = true;
このコメントアウトの行、不要でしたら削除をお願いします。

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Views/LoginPage.xaml.cs
> +            // btnStartShopping.IsVisible = false;
このコメントアウトの行、不要でしたら削除をお願いします。

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Views/LoginPage.xaml.cs
> +                //}
このコメントアウト行は不要でしたら削除をお願いします。

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/App.xaml.cs
> +
もし不要な空行であれば、削除お願いします。

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp.iOS/AppDelegate.cs
> +
もし不要な空行でしたら、削除をお願いします。

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp.iOS/AppDelegate.cs
> +                    Debug.WriteLine($"Unable to call unregister {error}");
この `Debug` の処理、もし簡単そうなら、 App Center の Analytics に流すようにできそうでしょうか？（見当違いのこと言っていたらすみません！

2020-09-30 17:47 UTC, dzeyelid commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp.Android/MainActivity.cs
> +                    Log.Debug(Constant.DebugTag, "This device is not supported");
この `Log` の処理、もし簡単そうなら、 App Center の Analytics に流すようにできそうでしょうか？

2020-09-30 17:55 UTC, dzeyelid commented
追加で、 App Center の Build の `Environment variables` の部分も更新いただけたら助かります 🙏 
https://github.com/intelligent-retail/smart-store/tree/mobile-notification-hub2/src/client-app

2020-10-01 06:41 UTC, masatoru commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Utilities/Mock.cs
> +                            ImageUrls=new []{ "https://www.morinaga.co.jp/dars/images/item_01_01.png" }
差し替えました。これは先日のデモの時のままでした（失礼しました）。

2020-10-01 06:43 UTC, masatoru commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Views/LoginPage.xaml.cs
> +                        // btnStartShopping.IsVisible = true;
削除しました。

2020-10-01 06:44 UTC, masatoru commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/Views/LoginPage.xaml.cs
> +            // btnStartShopping.IsVisible = false;
削除しました。

2020-10-01 06:44 UTC, masatoru commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp/App.xaml.cs
> +
削除しました。

2020-10-01 06:56 UTC, dzeyelid reviewed
@masatoru 追加でコメントしました、ご確認をよろしくお願いいたします 🙏

2020-10-01 06:56 UTC, dzeyelid commented on docs/notification-hubs.md
> +  - `NotificationHubName`: Notification Hub Namespace の値
Notification Hub の名前なのか、ネームスペースの名前なのか、明確にしていただけますか？（おそらく Hub の方の名前だと思っています。）

2020-10-01 06:56 UTC, dzeyelid commented on docs/notification-hubs.md
> +  - `HubName`: Notification Hub Namespace の値
上記同様に、Notification Hub の名前なのか、ネームスペースの名前なのか、明記をお願いいたします。

2020-10-01 07:01 UTC, masatoru commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp.iOS/AppDelegate.cs
> +                    Debug.WriteLine($"Unable to call unregister {error}");
Analytics.TrackEvent で AppCenter のログに流すようにしました。

2020-10-01 07:01 UTC, masatoru commented on src/client-app/SmartRetailApp/SmartRetailApp/SmartRetailApp.Android/MainActivity.cs
> +                    Log.Debug(Constant.DebugTag, "This device is not supported");
Analytics.TrackEvent で AppCenter のログに流すようにしました。

2020-10-01 07:40 UTC, masatoru commented on docs/notification-hubs.md
> +  - `NotificationHubName`: Notification Hub Namespace の値
修正しました。

2020-10-01 07:40 UTC, masatoru commented on docs/notification-hubs.md
> +  - `HubName`: Notification Hub Namespace の値
修正しました。

2020-10-01 10:21 UTC, dzeyelid approved these changes
@masatoru ご対応ありがとうございました！

2020-10-01 10:21 UTC, merged